name: Daily OIS Rate Report

on:
  schedule:
      # Runs at 7:00 AM UTC daily (adjust timezone as needed)
      # For UK time (GMT/BST), use 7:00 UTC for 7am GMT or 6:00 UTC for 7am BST
    - cron: '0 7 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  send-ois-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v9
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests openpyxl

    - name: Run OIS Daily Agent
      env:
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: |
        python3 ois_daily_agent.py

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ois-report-logs
        path: logs/*.log
        retention-days: 7
